function y = filtro_paso(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 05-Apr-2019 16:10:04
persistent Hd;
if isempty(Hd)
    
    N     = 10;    % Order
    Fpass = 0.45;  % Passband Frequency
    Fstop = 0.55;  % Stopband Frequency
    Apass = 5;     % Passband Ripple (dB)
    
    h = fdesign.lowpass('n,fp,fst,ap', N, Fpass, Fstop, Apass);
    
    Hd = design(h, 'ellip', ...
        'SOSScaleNorm', 'Linf');
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

